version: '3.7'
services:
  mongodb:
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017:27017'
    logging:
      driver: 'none'

  back:
    ports:
      - '3000:3000'

  ue_admin:
    build:
      context: .
      dockerfile: Dockerfile-ueadmin
      args:
        vue_app_back_auth_server: http://back:3000
        vue_app_back_api_server: http://back:3000
    ports:
      - '3840:80'
    dns:
      - 223.6.6.6
      - 223.5.5.5

  ue_mongo:
    build:
      context: .
      dockerfile: Dockerfile-uemongo
      args:
        vue_app_back_auth_server: http://back:3000
        vue_app_back_api_server: http://back:3000
    ports:
      - '3830:80'
    dns:
      - 223.6.6.6
      - 223.5.5.5
