#基于alpine的nodejs基础镜像
FROM node:12.10.0-alpine AS builder
MAINTAINER made nodejs by p21 from lit29@chinatelecom.cn
WORKDIR /usr/src/app
#Install dependencied of nodejs on alpine
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
COPY . .
# 生成.env文件
ARG vue_app_base_url
ARG vue_app_back_auth_base
ARG vue_app_back_auth_server
ARG vue_app_back_api_base
ARG vue_app_back_api_server
ARG vue_app_user_role

RUN echo VUE_APP_BASE_URL=$vue_app_base_url > ./ue_sale/.env && \
  echo VUE_APP_BACK_AUTH_BASE=$vue_app_back_auth_base >> ./ue_sale/.env && \
  echo VUE_APP_BACK_AUTH_SERVER=$vue_app_back_auth_server >> ./ue_sale/.env && \
  echo VUE_APP_BACK_API_BASE=$vue_app_back_api_base >> ./ue_sale/.env && \
  echo VUE_APP_BACK_API_SERVER=$vue_app_back_api_server >> ./ue_sale/.env && \
  echo VUE_APP_USER_ROLE=$vue_app_user_role >> ./ue_sale/.env

RUN cd ue_sale && cnpm install -save vuex && cnpm i &&  yarn build.lib

# 标准基础镜像（部署阶段）
FROM nginx:alpine

# 设置时区
RUN sed -i 's?http://dl-cdn.alpinelinux.org/?https://mirrors.aliyun.com/?' /etc/apk/repositories && \
  apk add -U tzdata && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  apk del tzdata

# 修改配置文件
ADD ./ue_sale/nginx.conf.template /etc/nginx/nginx.conf.template

ADD ./ue_sale/start_nginx.sh start_nginx.sh

RUN chmod +x start_nginx.sh

# 将代码放在指定位置
COPY --from=builder /usr/src/app/ue_sale/dist /usr/share/nginx/html

CMD ["./start_nginx.sh"]
