#基于alpine的nodejs基础镜像
FROM node:12.10.0-alpine AS builder
MAINTAINER made nodejs by p21 from lit29@chinatelecom.cn
WORKDIR /usr/src/app
#Install dependencied of nodejs on alpine
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
#Install node_modules
COPY . .
# 生成.env文件
ARG vue_app_title=管理端
ARG vue_app_base_url
ARG vue_app_back_auth_base
ARG vue_app_back_auth_server
ARG vue_app_back_api_base
ARG vue_app_back_api_server
ARG vue_app_back_api_fs
ARG vue_app_front_doceditor_add
ARG vue_app_front_doceditor_modify

RUN echo VUE_APP_TITLE=$vue_app_title > .env && \
  echo VUE_APP_BASE_URL=$vue_app_base_url >> .env && \
  echo VUE_APP_BACK_AUTH_BASE=$vue_app_back_auth_base >> .env && \
  echo VUE_APP_BACK_AUTH_SERVER=$vue_app_back_auth_server >> .env && \
  echo VUE_APP_BACK_API_BASE=$vue_app_back_api_base >> .env && \
  echo VUE_APP_BACK_API_SERVER=$vue_app_back_api_server >> .env && \
	echo VUE_APP_BACK_API_FS=$vue_app_back_api_fs >> .env && \
	echo VUE_APP_FRONT_DOCEDITOR_ADD=$vue_app_front_doceditor_add >> .env && \
	echo VUE_APP_FRONT_DOCEDITOR_MODIFY=$vue_app_front_doceditor_modify >> .env 

# 安装依赖包，构建代码
RUN cd ue_admin && cnpm i && yarn build

# 标准基础镜像（部署阶段）
FROM nginx:alpine

# 设置时区
RUN sed -i 's?http://dl-cdn.alpinelinux.org/?https://mirrors.aliyun.com/?' /etc/apk/repositories && \
  apk add -U tzdata && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  apk del tzdata

# 修改配置文件
ADD ./ue_admin/nginx.conf.template /etc/nginx/nginx.conf.template

ADD ./ue_admin/start_nginx.sh /usr/local/bin/start_nginx.sh

RUN chmod +x /usr/local/bin/start_nginx.sh

# 将构建阶段代码放在指定位置
COPY --from=builder /usr/src/app/ue_admin/dist /usr/share/nginx/html

CMD ["start_nginx.sh"]