version: '3.7'
services:
  back:
    build: ./back
    image: 42.99.2.53:18124/tms-mongodb/back:21.12.2
    container_name: tms-back
    environment:
      - NODE_ENV=production
      - TMS_APP_PORT=3000
      - TMS_APP_NAME=apiit-mongo-web
      - TMS_APP_LOG4JS_LEVEL=debug
      - TMS_FINDER_OUTDIR=/data/
      - TMS_FINDER_FS_ROOTDIR=/data/root
      - TMS_FINDER_FS_CUSTOMNAME=false
      - TMS_APP_ROUTER_AUTH=/apiit/auth
      - TMS_APP_ROUTER_CONTROLLER=/apiit/api
      - TMS_APP_ROUTER_FSDOMAIN=/apiit/fs
      - TMS_APP_ROUTER_PLUGIN=/apiit/plugin

      - TMS_MONGODB_HOST=172.16.157.19
      - TMS_MONGODB_PORT=27014
      - TMS_MONGODB_USER=root
      - TMS_MONGODB_PASSWORD=Zhcqg4l+u3njTzTf

      # Redis
      - TMS_REDIS_PREFIX=dev-op
      - TMS_REDIS_HOST=172.16.157.21
      - TMS_REDIS_PORT=6500
      - TMS_REDIS_EXPIRESIN=7200
      - TMS_REDIS_PWD=urYgbBtgqv
      - TMS_APP_DEFAULT_CREATETIME=TMS_DEFAULT_CREATE_TIME
      - TMS_APP_DEFAULT_UPDATETIME=TMS_DEFAULT_UPDATE_TIME
      - TMS_APP_DB_CREATETIME=createTime
      - TMS_APP_DB_UPDATETIME=updateTime
      - TMW_REALTIME_REPLICA=false
      # 鉴权机制【redis,jwt】
      - TMS_APP_AUTH_TYPE=redis
    command: [ 'node', 'server' ]
    ports:
      - '37001:3000'
    networks:
      - portal
  admin:
    build:
      context: .
      dockerfile: Dockerfile-ueadmin
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /apiit/admin
        vue_app_back_auth_base: /apiit/auth
        vue_app_back_api_base: /apiit/api
        vue_app_back_api_fs: /apiit/fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
        vue_app_storetoken_way: session
        VUE_APP_BACK_API_SERVER: http://back:3000
        VUE_APP_BACK_AUTH_SERVER: http://back:3000
    image: 42.99.2.53:18124/tms-mongodb/admin:21.12.2
    container_name: tms-admin
    environment:
      - NGINX_WEB_BASE_URL=/apiit/admin
    ports:
      - '37002:80'
    networks:
      - portal

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-uemongo
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /apiit/mongo
        vue_app_back_auth_base: /apiit/auth
        vue_app_back_api_base: /apiit/api
        vue_app_back_api_fs: /apiit/fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
        vue_app_front_batcheditor: ''
        vue_app_storetoken_way: session
        vue_app_pluginsub_names: ''
        VUE_APP_BACK_API_SERVER: http://back:3000
        VUE_APP_BACK_AUTH_SERVER: http://back:3000
    image: 42.99.2.53:18124/tms-mongodb/ue-mongo:21.12.2
    container_name: tms-mongodb-ue_mongo
    environment:
      - NGINX_WEB_BASE_URL=/apiit/mongo
    ports:
      - '37003:80'
    networks:
      - portal
networks:
  portal:
    driver: bridge
