# 标准基础镜像（构建阶段）
FROM node:alpine
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
WORKDIR /home/node/app
COPY . .
# 生成.env文件
ARG vue_app_title=订单用户端
ARG vue_app_base_url
ARG vue_app_back_auth_base
ARG vue_app_back_auth_server
ARG vue_app_back_api_base
ARG vue_app_back_api_server
ARG vue_app_back_api_plugin
ARG vue_app_back_api_fs
ARG vue_app_submit_valitor_field

RUN echo VUE_APP_TITLE=$vue_app_title > ./ue_mongo/.env && \
  echo VUE_APP_BASE_URL=$vue_app_base_url >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_AUTH_BASE=$vue_app_back_auth_base >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_AUTH_SERVER=$vue_app_back_auth_server >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_API_BASE=$vue_app_back_api_base >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_API_SERVER=$vue_app_back_api_server >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_API_PLUGIN=$vue_app_back_api_plugin >> ./ue_mongo/.env && \
  echo VUE_APP_BACK_API_FS=$vue_app_back_api_fs >> ./ue_mongo/.env && \
  echo VUE_APP_SUBMIT_VALITOR_FIELD=$vue_app_submit_valitor_field >> ./ue_mongo/.env


# 安装依赖包，构建代码
RUN cd ue_mongo && cnpm i && yarn build

# 标准基础镜像（部署阶段）
FROM nginx:alpine

# 设置时区
RUN sed -i 's?http://dl-cdn.alpinelinux.org/?https://mirrors.aliyun.com/?' /etc/apk/repositories && \
  apk add -U tzdata && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  apk del tzdata

# 修改配置文件
ADD ./ue_mongo/nginx.conf.template /etc/nginx/nginx.conf.template

ADD ./ue_mongo/start_nginx.sh /usr/local/bin/start_nginx.sh

RUN chmod +x /usr/local/bin/start_nginx.sh

# 将构建阶段代码放在指定位置
COPY --from=0 /home/node/app/ue_mongo/dist /usr/share/nginx/html

CMD ["start_nginx.sh"]

