version: '3.7'
services:
  back:
    build: ./back
    image: 192.168.253.28/tms-mongodb/back:latest
    container_name: gwit-back
    environment:
      - NODE_ENV=production
      - TMS_APP_PORT=3000
      - TMS_APP_NAME=apiit-mongo-web
      - TMS_APP_LOG4JS_LEVEL=debug
      - TMS_FINDER_OUTDIR=/data/
      - TMS_FINDER_FS_ROOTDIR=/data/root
      - TMS_FINDER_FS_CUSTOMNAME=true
      - TMS_APP_ROUTER_AUTH=/gwit/auth
      - TMS_APP_ROUTER_CONTROLLER=/gwit/api
      - TMS_APP_ROUTER_FSDOMAIN=/gwit/fs
      - TMS_APP_ROUTER_PLUGIN=/gwit/plugin

      - TMS_MONGODB_HOST=host.docker.internal
      - TMS_MONGODB_PORT=27017

      #- TMS_REDIS_EXPIRESIN=60
      - TMS_APP_DEFAULT_CREATETIME=TMS_DEFAULT_CREATE_TIME
      - TMS_APP_DEFAULT_UPDATETIME=TMS_DEFAULT_UPDATE_TIME
      - TMS_APP_DB_CREATETIME=createTime
      - TMS_APP_DB_UPDATETIME=updateTime
      - TMW_REALTIME_REPLICA=false
      # 鉴权机制【redis,jwt】
      - TMS_APP_AUTH_TYPE=redis
    command: [ 'node', 'server' ]
    ports:
      - '3000:3000'
    networks:
      - portal
  admin:
    build:
      context: .
      dockerfile: Dockerfile-ueadmin
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /gwit/admin
        vue_app_back_auth_base: /gwit/auth
        vue_app_back_api_base: /gwit/api
        vue_app_back_api_fs: /gwit/fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
        vue_app_storetoken_way: session
        VUE_APP_BACK_API_SERVER: http://back:3000
        VUE_APP_BACK_AUTH_SERVER: http://back:3000
    image: 192.168.253.28/tms-mongodb-gwit/admin:latest
    container_name: gwit-admin
    environment:
      - NGINX_WEB_BASE_URL=/gwit/admin
      # - NGINX_WEB_BACK_SERVER=http://back:3000
      # - NGINX_WEB_AUTH_URL=/gwit/auth
      # - NGINX_WEB_API_URL=/gwit/api
    ports:
      - '3840:80'
    networks:
      - portal

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-uemongo
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /gwit/mongo
        vue_app_back_auth_base: /gwit/auth
        vue_app_back_api_base: /gwit/api
        vue_app_back_api_fs: /gwit/fs
        vue_app_front_doceditor_add: ''
        vue_app_front_doceditor_modify: ''
        vue_app_front_batcheditor: ''
        vue_app_storetoken_way: session
        vue_app_pluginsub_names: ''
        VUE_APP_BACK_API_SERVER: http://back:3000
        VUE_APP_BACK_AUTH_SERVER: http://back:3000
    image: 192.168.253.28/tms-mongodb-gwit/mongo:latest
    container_name: gwit-mongo
    environment:
      - NGINX_WEB_BASE_URL=/gwit/mongo
      # - NGINX_WEB_BACK_SERVER=http://back:3000
      # - NGINX_WEB_AUTH_URL=/gwit/auth
      # - NGINX_WEB_API_URL=/gwit/api
    ports:
      - '3830:80'
    networks:
      - portal
networks:
  portal:
    driver: bridge
